language: c

services:
    - memcached

addons:
    apt:
        packages:
            - libmemcached-dev
            - valgrind

env:
    - LUA_VERSION=5.1.5
    - LUA_VERSION=5.2.4
    - LUA_VERSION=5.3.4
    - LUA_IMPL=luajit LUA_VERSION=2.0.5
    - LUA_IMPL=luajit LUA_VERSION=2.1.0-beta3

install:
    - make env LUA_IMPL=$LUA_IMPL LUA_VERSION=$LUA_VERSION

script:
    - make lib
    - make test
    - make qa
    - if [[ "$LUA_IMPL" != "luajit" ]]; then make valgrind-test; fi
