language: c

sudo: required

services:
    - memcached

before_install:
    - sudo apt-get remove --auto-remove -yqq libmemcached-dev
    - sudo add-apt-repository -y ppa:ondrej/php5
    - sudo apt-get -qq update
    - sudo apt-get install -yqq libmemcached-dev valgrind

env:
    - LUA_VERSION=5.1.5
    - LUA_VERSION=5.2.4
    - LUA_VERSION=5.3.1
    - LUA_IMPL=luajit LUA_VERSION=2.0.4
    - LUA_IMPL=luajit LUA_VERSION=2.1.0-beta1

install:
    - make env PLATFORM=linux LUA_IMPL=$LUA_IMPL LUA_VERSION=$LUA_VERSION
    - eval `env/bin/luarocks path`

script:
    - make lib LIBMEMCACHED_DIR=/usr
    - make test
    - if [[ "$LUA_IMPL" != *"luajit"* ]]; then make valgrind-test; fi
    - make qa
